# Fundamentals

A distilled version of [this](https://www.learnpytorch.io/00_pytorch_fundamentals/) page. Highly recommend going through it if you have time.

## Intro to Pytorch.

What is Pytorch? A framework to write ML/DL code in.

Why Pytorch? Because everyone doing defining research uses it, and it makes working with GPUs easy.

Alternatives? Jax, Tensorflow

Feel free to lead the original for more motivation if needed.

In [1]:
## Setup

import torch
torch.__version__

'2.10.0+cu128'

## Tensors

What are tensors? The most basic building block of pytorch. A generic way of representing a data.

A 0 dimensional (or 0-d) tensor is a scalar. 1-d tensor is a vector. A 2-d vector is a matrix. Think of tensors as a class of these objects.

[torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html) describes all the details about this class.

In [2]:
# Creating a tensor

first = torch.tensor(67)
first

tensor(67)

In [3]:
# dimension of a tensor

first.ndim

0

In [4]:
# turn back to int/float/whatever (only works for scalars)

second = first.item()
second

67

In [5]:
# creating a vector

third = torch.tensor([7,7])
third

tensor([7, 7])

In [6]:
third.ndim

1

In [7]:
## creating a matrix
fourth = torch.tensor([[1,2],
                       [3,4]])
fourth

tensor([[1, 2],
        [3, 4]])

In [8]:
fourth.ndim

2

How do you find dimensions of an arbitrary tensor?

Count the number of square brackets at the start.

### Shape vs ndim

ndim indicates the number of dimensions of a tensor, while shape provides a tuple with the size of each dimension.

In [9]:
# shape of a tensor

fourth.shape

torch.Size([2, 2])

In [10]:
third.shape

torch.Size([2])

In [11]:
first.shape

torch.Size([])

## Populating Tensors


How do we populate tensors with data?

In [12]:
#random data

fifth = torch.rand(size = (3,4))

# creates a 3x4 tensor with random numbers

fifth

tensor([[0.5982, 0.8176, 0.4842, 0.4833],
        [0.7829, 0.0718, 0.4474, 0.9484],
        [0.1291, 0.6838, 0.8922, 0.0022]])

In [13]:
fifth.ndim # should be 2

2

In [14]:
# zeroes and ones

sixth = torch.zeros(size = (3,4))
sixth

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
seventh = torch.zeros_like(fifth)

seventh

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
eight = torch.ones(size = (6,7))
eight

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# range of numbers

ninth = torch.range(start = 10, end = 1000, step = 25)

ninth

/tmp/ipykernel_9479/3095124406.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ninth = torch.range(start = 10, end = 1000, step = 25)


tensor([ 10.,  35.,  60.,  85., 110., 135., 160., 185., 210., 235., 260., 285.,
        310., 335., 360., 385., 410., 435., 460., 485., 510., 535., 560., 585.,
        610., 635., 660., 685., 710., 735., 760., 785., 810., 835., 860., 885.,
        910., 935., 960., 985.])

## Tensor Datatypes

Torch has different datatypes for tensors.

torch.cuda means that the tensor is used on the GPU.

torch.int8, torch.int16, torch.int32, torch.int64, torch.float16 are some other. These have to do with precision in computing, and are quite important when working with neural nets.

In [18]:
# Get datatype of tensor

sixth.dtype

torch.float32

In [19]:
# Set datatype of tensor

#dtype sets the datatype of the underlying data, device defines gpu/cpu and requires grad defines whether operations performed on this tensor will be stored or not, useful for stuff like backprop
tenth = torch.tensor([1,4,6], dtype = None, device = None, requires_grad = False)

tenth.dtype



torch.int64

In [20]:
# Change datatype of a tensor

deux = tenth.type(torch.float16)
deux.dtype

torch.float16

## Manipulating Tensors

In [21]:
# Tensor-scalar operations

sixth += 10
seventh -= 10
eight *= 6
ninth /= 25

sixth, seventh, eight, ninth




(tensor([[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]),
 tensor([[-10., -10., -10., -10.],
         [-10., -10., -10., -10.],
         [-10., -10., -10., -10.]]),
 tensor([[6., 6., 6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6., 6., 6.]]),
 tensor([ 0.4000,  1.4000,  2.4000,  3.4000,  4.4000,  5.4000,  6.4000,  7.4000,
          8.4000,  9.4000, 10.4000, 11.4000, 12.4000, 13.4000, 14.4000, 15.4000,
         16.4000, 17.4000, 18.4000, 19.4000, 20.4000, 21.4000, 22.4000, 23.4000,
         24.4000, 25.4000, 26.4000, 27.4000, 28.4000, 29.4000, 30.4000, 31.4000,
         32.4000, 33.4000, 34.4000, 35.4000, 36.4000, 37.4000, 38.4000, 39.4000]))

In [22]:
# Matmul

# For matmul the math has to hold, so the inner dimensions must match, and the resultant matrix with have the outer dimensions.

# so (a,b) X (b,c) will give a (a,c) matrix

# Shapes need to be in the right way  so this will return an error
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [23]:
# We fix this with a transpose!

# matrix.T gives the transpose of a matrix.

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [24]:
# Aggregation Operations

eleventh = torch.arange(0,50,10)

eleventh

tensor([ 0, 10, 20, 30, 40])

In [25]:
print(f"Minimum: {eleventh.min()}")
print(f"Maximum: {eleventh.max()}")
# print(f"Mean: {eleventh.mean()}") # this will error
print(f"Mean: {eleventh.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {eleventh.sum()}")

Minimum: 0
Maximum: 40
Mean: 20.0
Sum: 100


In [26]:
# Returns index of max and min values
print(f"Index where max value occurs: {eleventh.argmax()}")
print(f"Index where min value occurs: {eleventh.argmin()}")

Index where max value occurs: 4
Index where min value occurs: 0


In [27]:
# Reshaping a tensor
alpha = torch.arange(1.,8.,1)
alpha, alpha.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [28]:
# add an extra dim

beta = alpha.reshape(1,7)
beta

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [29]:
# stack tensors

gamma = torch.stack([beta, beta], dim = 0)
delta = torch.stack([beta,beta], dim = 1)
eps = torch.stack([beta, beta], dim = 2)
gamma, delta, eps

(tensor([[[1., 2., 3., 4., 5., 6., 7.]],
 
         [[1., 2., 3., 4., 5., 6., 7.]]]),
 tensor([[[1., 2., 3., 4., 5., 6., 7.],
          [1., 2., 3., 4., 5., 6., 7.]]]),
 tensor([[[1., 1.],
          [2., 2.],
          [3., 3.],
          [4., 4.],
          [5., 5.],
          [6., 6.],
          [7., 7.]]]))

`gamma = torch.stack([beta, beta], dim = 0) `stacks the tensors along a new dimension at index 0 (the first dimension). Since beta is a 1x7 tensor, stacking two beta tensors with dim=0 results in a 2x1x7 tensor. This means it adds new 'rows' of the beta tensors on top of each other.

`delta = torch.stack([beta,beta], dim = 1) `stacks the tensors along a new dimension at index 1 (the second dimension). For a 1x7 beta tensor, stacking with dim=1 results in a 1x2x7 tensor. This effectively adds new 'columns' of the beta tensors next to each other within the existing first dimension.

`eps = torch.stack([beta,beta], dim = 2) `stacks the tensors along a new dimension at index 2 (the third dimension). For a 1x7 beta tensor, stacking with dim=1 results in a 1x7x2 tensor.

As we can see, the first dimension of 1 is making things a little complicated here. Essentially we have a row that contains just 1 point `(which is just [[1.,2.,3.,4.,5.,6.,7.]]`. We can remove this

In [30]:
# remove dim of one

phi = eps.squeeze()
phi, phi.shape

(tensor([[1., 1.],
         [2., 2.],
         [3., 3.],
         [4., 4.],
         [5., 5.],
         [6., 6.],
         [7., 7.]]),
 torch.Size([7, 2]))

In [31]:
# reverse this process

sigma = phi.unsqueeze(dim = 0)

torch.equal(sigma, eps)

True

## Indexing

How do we select data from Tensors?

In [32]:
theta = phi.reshape(2,7,1)
theta

tensor([[[1.],
         [1.],
         [2.],
         [2.],
         [3.],
         [3.],
         [4.]],

        [[4.],
         [5.],
         [5.],
         [6.],
         [6.],
         [7.],
         [7.]]])

Indexing always goes from outermost bracket to innermost brackets

In [33]:
print("First row : \n",theta[0])
print("-"*60)
print("First row first column", theta[0][0])
print("-"*60)
print("First row first column first element", theta[0][0][0])


First row : 
 tensor([[1.],
        [1.],
        [2.],
        [2.],
        [3.],
        [3.],
        [4.]])
------------------------------------------------------------
First row first column tensor([1.])
------------------------------------------------------------
First row first column first element tensor(1.)


You can also extract entire dimensions for a particular index

In [34]:
theta[:,0] # all rows, first column

tensor([[1.],
        [4.]])

In [35]:
theta[:, 0:4,:] #all rows, columns 1 to 4, all elements

tensor([[[1.],
         [1.],
         [2.],
         [2.]],

        [[4.],
         [5.],
         [5.],
         [6.]]])

In [36]:
theta[:,:,0] # all rows, all columns, first (and only) element :remember size is (2,7,1)

tensor([[1., 1., 2., 2., 3., 3., 4.],
        [4., 5., 5., 6., 6., 7., 7.]])

## Reproducibility

If you want your randomly created tensors to be consistent across different runs, you can use torch.manual_seed(seed = int). Industry standard is 42, shoutout Hitchhiker's guide to the Galaxy.


## Devices

How to use torch on GPU, CPU, and Mac APU

In [37]:
# Check for GPU
torch.cuda.is_available()

# Use T4 from colab, what is output?

True

In [38]:
# Check for MPS
torch.backends.mps.is_available()

False

In [39]:
# set device

if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [40]:
# move to GPU/MPS

chi = phi.to("cuda")
chi.device

device(type='cuda', index=0)

In [41]:
# move back to CPU (why? Lot of stuff can't happen on GPU, like converting to Numpy)

re = chi.cpu().numpy()
re

array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.],
       [7., 7.]], dtype=float32)